# Generated by Django 3.2.6 on 2021-08-29 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=100)),
                ('exp', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('cash', models.IntegerField()),
                ('description', models.CharField(max_length=500)),
                ('locSystem', models.CharField(max_length=100)),
                ('passHash', models.CharField(max_length=500)),
                ('email', models.EmailField(max_length=254)),
                ('locX', models.FloatField()),
                ('locY', models.FloatField()),
                ('locZ', models.FloatField()),
                ('authTokens', models.ManyToManyField(to='users.AuthToken')),
            ],
        ),
    ]
