# Generated by Django 3.2.6 on 2021-08-30 02:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210829_0628'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('cash', models.IntegerField()),
                ('description', models.CharField(max_length=500)),
                ('stations', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PlayerFaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rep', models.IntegerField()),
                ('status', models.CharField(max_length=100)),
                ('faction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.faction')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.player')),
            ],
        ),
        migrations.AddField(
            model_name='player',
            name='factions',
            field=models.ManyToManyField(through='users.PlayerFaction', to='users.Faction'),
        ),
    ]
