# Generated by Django 3.0.5 on 2021-05-28 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Planet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('planetType', models.CharField(max_length=100)),
                ('mass', models.IntegerField()),
                ('radius', models.IntegerField()),
                ('temp', models.IntegerField()),
                ('atmos', models.IntegerField()),
                ('seed', models.IntegerField()),
                ('rSpeed', models.IntegerField()),
                ('orbit', models.CharField(max_length=100)),
                ('orbitRadius', models.IntegerField()),
                ('moons', models.ManyToManyField(related_name='_planet_moons_+', to='solapi.Planet')),
            ],
        ),
        migrations.CreateModel(
            name='Star',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('sunType', models.CharField(max_length=100)),
                ('mass', models.IntegerField()),
                ('radius', models.IntegerField()),
                ('temp', models.IntegerField()),
                ('orbit', models.CharField(max_length=100)),
                ('orbitRadius', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='System',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('planets', models.ManyToManyField(to='solapi.Planet')),
                ('stars', models.ManyToManyField(to='solapi.Star')),
            ],
        ),
    ]
