# Generated by Django 3.2.3 on 2021-07-20 04:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('solapi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Atmosphere',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('presure', models.FloatField()),
                ('nitrogen', models.FloatField()),
                ('oxygen', models.FloatField()),
                ('argon', models.FloatField()),
                ('carbonDioxide', models.FloatField()),
                ('neon', models.FloatField()),
                ('helium', models.FloatField()),
                ('methane', models.FloatField()),
                ('sulpherDioxide', models.FloatField()),
                ('hydrogen', models.FloatField()),
                ('sodium', models.FloatField()),
                ('potasium', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Orbit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a', models.FloatField()),
                ('exentricity', models.FloatField()),
                ('b', models.FloatField()),
                ('p', models.FloatField()),
                ('period', models.FloatField()),
                ('rotation', models.FloatField()),
                ('bigM', models.FloatField()),
            ],
        ),
        migrations.RenameField(
            model_name='star',
            old_name='sunType',
            new_name='seed',
        ),
        migrations.RemoveField(
            model_name='planet',
            name='atmos',
        ),
        migrations.RemoveField(
            model_name='planet',
            name='orbitRadius',
        ),
        migrations.RemoveField(
            model_name='planet',
            name='rSpeed',
        ),
        migrations.RemoveField(
            model_name='planet',
            name='temp',
        ),
        migrations.RemoveField(
            model_name='star',
            name='orbitRadius',
        ),
        migrations.RemoveField(
            model_name='star',
            name='temp',
        ),
        migrations.AddField(
            model_name='planet',
            name='axis',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='planet',
            name='gravity',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='planet',
            name='tilt',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='star',
            name='starClass',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='star',
            name='temperature',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='system',
            name='seed',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='planet',
            name='mass',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='planet',
            name='radius',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='planet',
            name='seed',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='star',
            name='mass',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='star',
            name='radius',
            field=models.FloatField(),
        ),
        migrations.AddField(
            model_name='planet',
            name='atmosphere',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='solapi.atmosphere'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='system',
            name='orbit',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='solapi.orbit'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='planet',
            name='orbit',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='solapi.orbit'),
        ),
        migrations.AlterField(
            model_name='star',
            name='orbit',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='solapi.orbit'),
        ),
    ]
