# Generated by Django 3.2.6 on 2021-08-29 03:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('solapi', '0002_auto_20210720_0442'),
    ]

    operations = [
        migrations.CreateModel(
            name='Element',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('stable', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='atmosphere',
            name='argon',
        ),
        migrations.RemoveField(
            model_name='atmosphere',
            name='carbonDioxide',
        ),
        migrations.RemoveField(
            model_name='atmosphere',
            name='helium',
        ),
        migrations.RemoveField(
            model_name='atmosphere',
            name='hydrogen',
        ),
        migrations.RemoveField(
            model_name='atmosphere',
            name='methane',
        ),
        migrations.RemoveField(
            model_name='atmosphere',
            name='neon',
        ),
        migrations.RemoveField(
            model_name='atmosphere',
            name='nitrogen',
        ),
        migrations.RemoveField(
            model_name='atmosphere',
            name='oxygen',
        ),
        migrations.RemoveField(
            model_name='atmosphere',
            name='potasium',
        ),
        migrations.RemoveField(
            model_name='atmosphere',
            name='sodium',
        ),
        migrations.RemoveField(
            model_name='atmosphere',
            name='sulpherDioxide',
        ),
        migrations.AddField(
            model_name='planet',
            name='description',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='star',
            name='description',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='system',
            name='description',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Asteroid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('seed', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=500)),
                ('type', models.CharField(max_length=100)),
                ('l', models.FloatField()),
                ('k', models.FloatField()),
                ('elemants', models.ManyToManyField(to='solapi.Element')),
                ('orbit', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='solapi.orbit')),
            ],
        ),
        migrations.AddField(
            model_name='atmosphere',
            name='elemants',
            field=models.ManyToManyField(to='solapi.Element'),
        ),
        migrations.AddField(
            model_name='planet',
            name='elemants',
            field=models.ManyToManyField(to='solapi.Element'),
        ),
        migrations.AddField(
            model_name='system',
            name='asteroids',
            field=models.ManyToManyField(to='solapi.Asteroid'),
        ),
    ]
